ALTER TABLE "Devices" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "Devices" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
ALTER TABLE "Devices" ADD COLUMN IF NOT EXISTS "address" TEXT;
