ALTER TABLE "ManageEmployee" ADD COLUMN IF NOT EXISTS "aadharNo" VARCHAR;
ALTER TABLE "ManageEmployee" ADD COLUMN IF NOT EXISTS "panNo" VARCHAR;
ALTER TABLE "ManageEmployee" ADD COLUMN IF NOT EXISTS "uanNo" VARCHAR;
ALTER TABLE "ManageEmployee" ADD COLUMN IF NOT EXISTS "esiNo" VARCHAR;
