import type { Employee, OrgChartData } from "./types";

/**
 * Realistic demo org used when the HRMS hierarchy API is unavailable.
 * Replace via `loadOrgChartData()` in `mapApiToOrgData.ts`.
 */
const employees: Employee[] = [
  {
    id: "e-ceo",
    name: "Elena Voss",
    title: "Chief Executive Officer",
    avatar: "",
    department: "Executive",
    location: "San Francisco",
    managerId: null,
    email: "elena.voss@acme.example",
    phone: "+1 415 555 0101",
    joinedDate: "2018-03-12",
    directReportCount: 4,
    status: "active",
    employeeCode: "EMP-1001",
    isL1: true,
    isCompanyOwner: true,
  },
  {
    id: "e-hr",
    name: "Marcus Chen",
    title: "HR Director",
    avatar: "",
    department: "People Operations",
    location: "San Francisco",
    managerId: "e-ceo",
    email: "marcus.chen@acme.example",
    phone: "+1 415 555 0110",
    joinedDate: "2019-06-03",
    directReportCount: 2,
    status: "active",
    employeeCode: "EMP-1040",
  },
  {
    id: "e-eng",
    name: "Jordan Hale",
    title: "Engineering Director",
    avatar: "",
    department: "Engineering",
    location: "Austin",
    managerId: "e-ceo",
    email: "jordan.hale@acme.example",
    phone: "+1 512 555 0140",
    joinedDate: "2019-01-21",
    directReportCount: 3,
    status: "active",
    employeeCode: "EMP-1100",
  },
  {
    id: "e-prod",
    name: "Sofia Alvarez",
    title: "Product Director",
    avatar: "",
    department: "Product",
    location: "New York",
    managerId: "e-ceo",
    email: "sofia.alvarez@acme.example",
    phone: "+1 212 555 0188",
    joinedDate: "2020-02-11",
    directReportCount: 2,
    status: "active",
    employeeCode: "EMP-1200",
  },
  {
    id: "e-fin",
    name: "David Okonkwo",
    title: "Finance Director",
    avatar: "",
    department: "Finance",
    location: "San Francisco",
    managerId: "e-ceo",
    email: "david.okonkwo@acme.example",
    phone: "+1 415 555 0166",
    joinedDate: "2018-11-08",
    directReportCount: 2,
    status: "active",
    employeeCode: "EMP-1300",
  },
  {
    id: "e-hr-mgr",
    name: "Aisha Rahman",
    title: "HR Manager",
    avatar: "",
    department: "People Operations",
    location: "San Francisco",
    managerId: "e-hr",
    email: "aisha.rahman@acme.example",
    phone: "+1 415 555 0112",
    joinedDate: "2021-04-19",
    directReportCount: 2,
    status: "active",
    employeeCode: "EMP-1044",
  },
  {
    id: "e-hr-bp",
    name: "Noah Patel",
    title: "HR Business Partner",
    avatar: "",
    department: "People Operations",
    location: "Austin",
    managerId: "e-hr-mgr",
    email: "noah.patel@acme.example",
    phone: "+1 512 555 0118",
    joinedDate: "2022-08-01",
    directReportCount: 0,
    status: "active",
    employeeCode: "EMP-1048",
  },
  {
    id: "e-hr-rec",
    name: "Maya Brooks",
    title: "Talent Acquisition Lead",
    avatar: "",
    department: "People Operations",
    location: "New York",
    managerId: "e-hr-mgr",
    email: "maya.brooks@acme.example",
    phone: "+1 212 555 0122",
    joinedDate: "2023-01-16",
    directReportCount: 0,
    status: "active",
    employeeCode: "EMP-1051",
  },
  {
    id: "e-eng-plat",
    name: "Chris Nguyen",
    title: "Platform Engineering Manager",
    avatar: "",
    department: "Engineering",
    location: "Austin",
    managerId: "e-eng",
    email: "chris.nguyen@acme.example",
    phone: "+1 512 555 0144",
    joinedDate: "2020-05-04",
    directReportCount: 2,
    status: "active",
    employeeCode: "EMP-1110",
  },
  {
    id: "e-eng-app",
    name: "Priya Shah",
    title: "Application Engineering Manager",
    avatar: "",
    department: "Engineering",
    location: "Austin",
    managerId: "e-eng",
    email: "priya.shah@acme.example",
    phone: "+1 512 555 0148",
    joinedDate: "2021-09-13",
    directReportCount: 2,
    status: "active",
    employeeCode: "EMP-1120",
  },
  {
    id: "e-eng-qa",
    name: "Luis Romero",
    title: "QA Manager",
    avatar: "",
    department: "Engineering",
    location: "Austin",
    managerId: "e-eng",
    email: "luis.romero@acme.example",
    phone: "+1 512 555 0152",
    joinedDate: "2022-03-07",
    directReportCount: 1,
    status: "active",
    employeeCode: "EMP-1130",
  },
  {
    id: "e-eng-ic1",
    name: "Hannah Kim",
    title: "Senior Backend Engineer",
    avatar: "",
    department: "Engineering",
    location: "Austin",
    managerId: "e-eng-plat",
    email: "hannah.kim@acme.example",
    phone: "+1 512 555 0155",
    joinedDate: "2022-11-02",
    directReportCount: 0,
    status: "active",
    employeeCode: "EMP-1114",
  },
  {
    id: "e-eng-ic2",
    name: "Owen Blake",
    title: "Infrastructure Engineer",
    avatar: "",
    department: "Engineering",
    location: "San Francisco",
    managerId: "e-eng-plat",
    email: "owen.blake@acme.example",
    phone: "+1 415 555 0158",
    joinedDate: "2023-06-20",
    directReportCount: 0,
    status: "active",
    employeeCode: "EMP-1117",
  },
  {
    id: "e-eng-ic3",
    name: "Rita Das",
    title: "Frontend Engineer",
    avatar: "",
    department: "Engineering",
    location: "New York",
    managerId: "e-eng-app",
    email: "rita.das@acme.example",
    phone: "+1 212 555 0160",
    joinedDate: "2024-02-05",
    directReportCount: 0,
    status: "active",
    employeeCode: "EMP-1124",
  },
  {
    id: "e-eng-ic4",
    name: "Tomás Silva",
    title: "Mobile Engineer",
    avatar: "",
    department: "Engineering",
    location: "Austin",
    managerId: "e-eng-app",
    email: "tomas.silva@acme.example",
    phone: "+1 512 555 0162",
    joinedDate: "2024-07-15",
    directReportCount: 0,
    status: "active",
    employeeCode: "EMP-1128",
  },
  {
    id: "e-qa-ic",
    name: "Leah Grant",
    title: "QA Engineer",
    avatar: "",
    department: "Engineering",
    location: "Austin",
    managerId: "e-eng-qa",
    email: "leah.grant@acme.example",
    phone: "+1 512 555 0164",
    joinedDate: "2023-10-09",
    directReportCount: 0,
    status: "active",
    employeeCode: "EMP-1133",
  },
  {
    id: "e-pm",
    name: "Daniel Cho",
    title: "Senior Product Manager",
    avatar: "",
    department: "Product",
    location: "New York",
    managerId: "e-prod",
    email: "daniel.cho@acme.example",
    phone: "+1 212 555 0190",
    joinedDate: "2021-07-26",
    directReportCount: 1,
    status: "active",
    employeeCode: "EMP-1208",
  },
  {
    id: "e-des",
    name: "Amelia Hart",
    title: "Product Designer",
    avatar: "",
    department: "Product",
    location: "New York",
    managerId: "e-prod",
    email: "amelia.hart@acme.example",
    phone: "+1 212 555 0194",
    joinedDate: "2023-03-14",
    directReportCount: 0,
    status: "active",
    employeeCode: "EMP-1215",
  },
  {
    id: "e-pm-ic",
    name: "Ben Carter",
    title: "Associate Product Manager",
    avatar: "",
    department: "Product",
    location: "San Francisco",
    managerId: "e-pm",
    email: "ben.carter@acme.example",
    phone: "+1 415 555 0196",
    joinedDate: "2025-01-06",
    directReportCount: 0,
    status: "active",
    employeeCode: "EMP-1211",
  },
  {
    id: "e-fin-mgr",
    name: "Helen Park",
    title: "Finance Manager",
    avatar: "",
    department: "Finance",
    location: "San Francisco",
    managerId: "e-fin",
    email: "helen.park@acme.example",
    phone: "+1 415 555 0170",
    joinedDate: "2020-09-28",
    directReportCount: 1,
    status: "active",
    employeeCode: "EMP-1308",
  },
  {
    id: "e-acc",
    name: "Ibrahim Nasser",
    title: "Staff Accountant",
    avatar: "",
    department: "Finance",
    location: "San Francisco",
    managerId: "e-fin",
    email: "ibrahim.nasser@acme.example",
    phone: "+1 415 555 0174",
    joinedDate: "2022-12-01",
    directReportCount: 0,
    status: "active",
    employeeCode: "EMP-1312",
  },
  {
    id: "e-fin-ic",
    name: "Grace Liu",
    title: "Payroll Specialist",
    avatar: "",
    department: "Finance",
    location: "Austin",
    managerId: "e-fin-mgr",
    email: "grace.liu@acme.example",
    phone: "+1 512 555 0178",
    joinedDate: "2024-04-22",
    directReportCount: 0,
    status: "active",
    employeeCode: "EMP-1316",
  },
];

export const MOCK_ORG_CHART: OrgChartData = {
  company: {
    id: "company",
    name: "Acme Corporation",
    logoUrl: null,
  },
  employees,
  departments: [
    { id: "d-eng", name: "Engineering", location: "Austin", employeeCount: 8, parentDepartmentId: null },
    { id: "d-people", name: "People Operations", location: "San Francisco", employeeCount: 4, parentDepartmentId: null },
    { id: "d-product", name: "Product", location: "New York", employeeCount: 4, parentDepartmentId: null },
    { id: "d-finance", name: "Finance", location: "San Francisco", employeeCount: 4, parentDepartmentId: null },
  ],
};
